export type {
  CaptureConsentDto,
  ChildDto,
  ConsentRecordDto,
  ConsentStatusDto,
  CreateChildDto,
  CreateGuardianDto,
  GuardianDto,
  IntakeStatusDto,
  MedicationEntry,
  PaginatedChildDto,
  UpdateChildDto,
  UpdateGuardianDto,
  UpsertMedicalHistoryDto,
  WithdrawConsentDto,
} from '../schemas/child.schema';
