export interface GameAsset {
	key: string;
	url: string;
}

export interface GameEntry {
	name: string;
	version: string;
	title: string;
	description: string;
	entryScenes: string[];
	supportedLevels: number[];
	/**
	 * Default session budget in seconds. URL `?totalTime=N` overrides
	 * this if supplied. Each game scene can also override per-level via
	 * its own LEVELS map; the precedence chain is documented in AGENTS.md.
	 */
	totalTimeSec: number;
	path: string;
	assets: {
		images?: GameAsset[];
		audio?: GameAsset[];
	};
}

export const GAME_REGISTRY: Record<string, GameEntry> = {
	calibration: {
		name: "calibration",
		version: "1-0-0",
		title: "calibration",
		description: "calibration for the tracking",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 60,
		path: "/trail_games/trail-games/calibration.html",
		assets: {},
	},
	"template-trail": {
		name: "template-trail",
		version: "1-0-0",
		title: "template-trail",
		description: "Test all trail effects in one game",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/trail-games/template-trail.html",
		assets: {},
	},
	"template-reveal": {
		name: "template-reveal",
		version: "1-0-0",
		title: "Template Reveal",
		description: "Scratch to reveal a hidden picture",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/reveal-games/template-reveal.html",
		assets: {},
	},
	"reveal-animals": {
		name: "reveal-animals",
		version: "1-0-0",
		title: "Reveal Animals",
		description: "Scratch to reveal an animal friend",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/reveal-games/reveal-animals.html",
		assets: {},
	},
	"reveal-vehicles": {
		name: "reveal-vehicles",
		version: "1-0-0",
		title: "Reveal Vehicles",
		description: "Scratch to reveal a vehicle surprise",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/reveal-games/reveal-vehicles.html",
		assets: {},
	},
	"reveal-fruits": {
		name: "reveal-fruits",
		version: "1-0-0",
		title: "Reveal Fruits",
		description: "Scratch to reveal a yummy fruit",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/reveal-games/reveal-fruits.html",
		assets: {},
	},
	"reveal-birds": {
		name: "reveal-birds",
		version: "1-0-0",
		title: "Reveal Birds",
		description: "Scratch to reveal a feathered friend",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/reveal-games/reveal-birds.html",
		assets: {},
	},
	"reveal-flowers": {
		name: "reveal-flowers",
		version: "1-0-0",
		title: "Reveal Flowers",
		description: "Scratch to reveal a pretty flower",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/reveal-games/reveal-flowers.html",
		assets: {},
	},
	"guess-animals": {
		name: "guess-animals",
		version: "1-0-0",
		title: "Guess the Animal",
		description: "Scratch, then guess what's hiding!",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/reveal-guess-games/guess-animals.html",
		assets: {},
	},
	"guess-fruits": {
		name: "guess-fruits",
		version: "1-0-0",
		title: "Guess the Fruit",
		description: "Scratch, then guess what's hiding!",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/reveal-guess-games/guess-fruits.html",
		assets: {},
	},
	"scatter-fruit": {
		name: "scatter-fruit",
		version: "1-0-0",
		title: "Scatter Fruit",
		description: "Sweep juicy fruits around the garden",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/sensory-games/scatter-fruit.html",
		assets: {},
	},
	"scatter-shells": {
		name: "scatter-shells",
		version: "1-0-0",
		title: "Scatter Shells",
		description: "Sweep seashells across the beach",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/sensory-games/scatter-shells.html",
		assets: {},
	},
	"scatter-leaf": {
		name: "scatter-leaf",
		version: "1-0-0",
		title: "Scatter Leaf",
		description: "Scatter autumn leaves in the breeze",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/sensory-games/scatter-leaf.html",
		assets: {},
	},
	"water-walk": {
		name: "water-walk",
		version: "1-0-0",
		title: "Water Walk",
		description: "Make ripples as you walk the lake",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/sensory-games/water-walk.html",
		assets: {},
	},
	"trail-stardust": {
		name: "trail-stardust",
		version: "1-0-0",
		title: "Star Dust",
		description: "Gentle falling star dust trail",
		entryScenes: ["SingleTrailScene_stardust"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-stardust.html",
		assets: {},
	},
	"trail-paint": {
		name: "trail-paint",
		version: "1-0-0",
		title: "Paint Splash",
		description: "Colorful paint splatter trail",
		entryScenes: ["SingleTrailScene_paint"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-paint.html",
		assets: {},
	},
	"trail-snow": {
		name: "trail-snow",
		version: "1-0-0",
		title: "Snow",
		description: "Gentle snowfall trail",
		entryScenes: ["SingleTrailScene_snow"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-snow.html",
		assets: {},
	},
	"trail-ember": {
		name: "trail-ember",
		version: "1-0-0",
		title: "Ember",
		description: "Floating ember glow trail",
		entryScenes: ["SingleTrailScene_ember"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-ember.html",
		assets: {},
	},
	"trail-magic-sparkle": {
		name: "trail-magic-sparkle",
		version: "1-0-0",
		title: "Magic Sparkle",
		description: "Twinkling magical star trail",
		entryScenes: ["SingleTrailScene_magic-sparkle"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-magic-sparkle.html",
		assets: {},
	},
	"trail-galaxy": {
		name: "trail-galaxy",
		version: "1-0-0",
		title: "Galaxy",
		description: "Swirling cosmic galaxy trail",
		entryScenes: ["SingleTrailScene_galaxy"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-galaxy.html",
		assets: {},
	},
	"trail-bubble": {
		name: "trail-bubble",
		version: "1-0-0",
		title: "Bubble",
		description: "Floating soap bubble trail",
		entryScenes: ["SingleTrailScene_bubble"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-bubble.html",
		assets: {},
	},
	"trail-glitter": {
		name: "trail-glitter",
		version: "1-0-0",
		title: "Glitter",
		description: "Sparkling diamond glitter trail",
		entryScenes: ["SingleTrailScene_glitter"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-glitter.html",
		assets: {},
	},
	"trail-firefly": {
		name: "trail-firefly",
		version: "1-0-0",
		title: "Firefly",
		description: "Gentle firefly glow trail",
		entryScenes: ["SingleTrailScene_firefly"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-firefly.html",
		assets: {},
	},
	"trail-rainbow-lines": {
		name: "trail-rainbow-lines",
		version: "1-0-0",
		title: "Rainbow Lines",
		description: "Flowing rainbow ribbon trail",
		entryScenes: ["SingleTrailScene_rainbow-lines"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-rainbow-lines.html",
		assets: {},
	},
	"trail-heart": {
		name: "trail-heart",
		version: "1-0-0",
		title: "Heart",
		description: "Floating heart trail",
		entryScenes: ["SingleTrailScene_heart"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-heart.html",
		assets: {},
	},
	"trail-rainbow-swirl": {
		name: "trail-rainbow-swirl",
		version: "1-0-0",
		title: "Rainbow Swirl",
		description: "Spinning rainbow star trail",
		entryScenes: ["SingleTrailScene_rainbow-swirl"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-rainbow-swirl.html",
		assets: {},
	},
	"trail-cloud-puff": {
		name: "trail-cloud-puff",
		version: "1-0-0",
		title: "Cloud Puff",
		description: "Fluffy cloud puff trail",
		entryScenes: ["SingleTrailScene_cloud-puff"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-cloud-puff.html",
		assets: {},
	},
	"trail-candy-drop": {
		name: "trail-candy-drop",
		version: "1-0-0",
		title: "Candy Drops",
		description: "Bouncing candy drop trail",
		entryScenes: ["SingleTrailScene_candy-drop"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-candy-drop.html",
		assets: {},
	},
	"trail-teddy-print": {
		name: "trail-teddy-print",
		version: "1-0-0",
		title: "Teddy Prints",
		description: "Cute teddy bear paw print trail",
		entryScenes: ["SingleTrailScene_teddy-print"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-teddy-print.html",
		assets: {},
	},
	"trail-firework": {
		name: "trail-firework",
		version: "1-0-0",
		title: "Firework",
		description: "Explosive firework spark trail",
		entryScenes: ["SingleTrailScene_firework"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-firework.html",
		assets: {},
	},
	"trail-underwater-bubble": {
		name: "trail-underwater-bubble",
		version: "1-0-0",
		title: "Bubble",
		description: "Underwater bubble trail",
		entryScenes: ["SingleTrailScene_underwater-bubble"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-underwater-bubble.html",
		assets: {},
	},
	"trail-ice-crystal": {
		name: "trail-ice-crystal",
		version: "1-0-0",
		title: "Ice Crystal",
		description: "Frosty ice crystal trail",
		entryScenes: ["SingleTrailScene_ice-crystal"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-ice-crystal.html",
		assets: {},
	},
	"trail-flower-garden": {
		name: "trail-flower-garden",
		version: "1-0-0",
		title: "Flower Garden",
		description: "Falling flower petal trail",
		entryScenes: ["SingleTrailScene_flower-garden"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-flower-garden.html",
		assets: {},
	},
	"trail-confetti": {
		name: "trail-confetti",
		version: "1-0-0",
		title: "Confetti",
		description: "Celebration confetti burst trail",
		entryScenes: ["SingleTrailScene_confetti"],
		supportedLevels: [1],
		totalTimeSec: 300,
		path: "/trail_games/trail-games/trail-confetti.html",
		assets: {},
	},
	"paint-floor": {
		name: "paint-floor",
		version: "1-0-0",
		title: "Paint Floor",
		description:
			"Paint the floor by walking — choose shapes, colors, and blend modes",
		entryScenes: ["PaintFloorScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/draw-games/paint-floor.html",
		assets: {},
	},
	"drawing-floor": {
		name: "drawing-floor",
		version: "1-0-0",
		title: "Drawing Floor",
		description:
			"Draw on the floor — pick colors, shapes, and sizes, then erase or save your artwork",
		entryScenes: ["GameScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/draw-games/drawing-floor.html",
		assets: {},
	},
	"trace-walk-number": {
		name: "trace-walk-number",
		version: "1-0-0",
		title: "Trace Walk - Numbers",
		description: "Walk to trace numbers and fill them in with color",
		entryScenes: ["TraceWalkNumberScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/draw-games/trace-walk-number.html",
		assets: {},
	},
	"trace-walk-alphabet": {
		name: "trace-walk-alphabet",
		version: "1-0-0",
		title: "Trace Walk - Alphabet",
		description: "Walk to trace letters and fill them in with color",
		entryScenes: ["TraceWalkAlphabetScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/draw-games/trace-walk-alphabet.html",
		assets: {},
	},
	"trace-walk-shapes": {
		name: "trace-walk-shapes",
		version: "1-0-0",
		title: "Trace Walk - Shapes",
		description: "Walk to trace shapes and fill them in with color",
		entryScenes: ["TraceWalkShapesScene"],
		supportedLevels: [1],
		totalTimeSec: 600,
		path: "/trail_games/draw-games/trace-walk-shapes.html",
		assets: {},
	},
};

export function getGameEntry(gameName: string): GameEntry | undefined {
	return GAME_REGISTRY[gameName];
}

export function getAllGameNames(): string[] {
	return Object.keys(GAME_REGISTRY);
}
