/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiTestRouteImport } from './routes/ui-test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsStaffIndexRouteImport } from './routes/_authenticated/settings/staff/index'
import { Route as AuthenticatedSettingsRoomsIndexRouteImport } from './routes/_authenticated/settings/rooms/index'
import { Route as AuthenticatedSettingsDepartmentsIndexRouteImport } from './routes/_authenticated/settings/departments/index'
import { Route as AuthenticatedPlatformClinicsIndexRouteImport } from './routes/_authenticated/platform/clinics/index'
import { Route as AuthenticatedSettingsStaffInviteRouteImport } from './routes/_authenticated/settings/staff/invite'
import { Route as AuthenticatedSettingsStaffStaffIdRouteImport } from './routes/_authenticated/settings/staff/$staffId'
import { Route as AuthenticatedSettingsRoomsNewRouteImport } from './routes/_authenticated/settings/rooms/new'
import { Route as AuthenticatedSettingsRoomsRoomIdRouteImport } from './routes/_authenticated/settings/rooms/$roomId'
import { Route as AuthenticatedSettingsDepartmentsNewRouteImport } from './routes/_authenticated/settings/departments/new'
import { Route as AuthenticatedSettingsDepartmentsDepartmentIdRouteImport } from './routes/_authenticated/settings/departments/$departmentId'
import { Route as AuthenticatedPlatformClinicsNewRouteImport } from './routes/_authenticated/platform/clinics/new'

const UiTestRoute = UiTestRouteImport.update({
  id: '/ui-test',
  path: '/ui-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsStaffIndexRoute =
  AuthenticatedSettingsStaffIndexRouteImport.update({
    id: '/settings/staff/',
    path: '/settings/staff/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoomsIndexRoute =
  AuthenticatedSettingsRoomsIndexRouteImport.update({
    id: '/settings/rooms/',
    path: '/settings/rooms/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsDepartmentsIndexRoute =
  AuthenticatedSettingsDepartmentsIndexRouteImport.update({
    id: '/settings/departments/',
    path: '/settings/departments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformClinicsIndexRoute =
  AuthenticatedPlatformClinicsIndexRouteImport.update({
    id: '/platform/clinics/',
    path: '/platform/clinics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsStaffInviteRoute =
  AuthenticatedSettingsStaffInviteRouteImport.update({
    id: '/settings/staff/invite',
    path: '/settings/staff/invite',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsStaffStaffIdRoute =
  AuthenticatedSettingsStaffStaffIdRouteImport.update({
    id: '/settings/staff/$staffId',
    path: '/settings/staff/$staffId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoomsNewRoute =
  AuthenticatedSettingsRoomsNewRouteImport.update({
    id: '/settings/rooms/new',
    path: '/settings/rooms/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoomsRoomIdRoute =
  AuthenticatedSettingsRoomsRoomIdRouteImport.update({
    id: '/settings/rooms/$roomId',
    path: '/settings/rooms/$roomId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsDepartmentsNewRoute =
  AuthenticatedSettingsDepartmentsNewRouteImport.update({
    id: '/settings/departments/new',
    path: '/settings/departments/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsDepartmentsDepartmentIdRoute =
  AuthenticatedSettingsDepartmentsDepartmentIdRouteImport.update({
    id: '/settings/departments/$departmentId',
    path: '/settings/departments/$departmentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformClinicsNewRoute =
  AuthenticatedPlatformClinicsNewRouteImport.update({
    id: '/platform/clinics/new',
    path: '/platform/clinics/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/ui-test': typeof UiTestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/platform/clinics/new': typeof AuthenticatedPlatformClinicsNewRoute
  '/settings/departments/$departmentId': typeof AuthenticatedSettingsDepartmentsDepartmentIdRoute
  '/settings/departments/new': typeof AuthenticatedSettingsDepartmentsNewRoute
  '/settings/rooms/$roomId': typeof AuthenticatedSettingsRoomsRoomIdRoute
  '/settings/rooms/new': typeof AuthenticatedSettingsRoomsNewRoute
  '/settings/staff/$staffId': typeof AuthenticatedSettingsStaffStaffIdRoute
  '/settings/staff/invite': typeof AuthenticatedSettingsStaffInviteRoute
  '/platform/clinics/': typeof AuthenticatedPlatformClinicsIndexRoute
  '/settings/departments/': typeof AuthenticatedSettingsDepartmentsIndexRoute
  '/settings/rooms/': typeof AuthenticatedSettingsRoomsIndexRoute
  '/settings/staff/': typeof AuthenticatedSettingsStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/ui-test': typeof UiTestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/platform/clinics/new': typeof AuthenticatedPlatformClinicsNewRoute
  '/settings/departments/$departmentId': typeof AuthenticatedSettingsDepartmentsDepartmentIdRoute
  '/settings/departments/new': typeof AuthenticatedSettingsDepartmentsNewRoute
  '/settings/rooms/$roomId': typeof AuthenticatedSettingsRoomsRoomIdRoute
  '/settings/rooms/new': typeof AuthenticatedSettingsRoomsNewRoute
  '/settings/staff/$staffId': typeof AuthenticatedSettingsStaffStaffIdRoute
  '/settings/staff/invite': typeof AuthenticatedSettingsStaffInviteRoute
  '/platform/clinics': typeof AuthenticatedPlatformClinicsIndexRoute
  '/settings/departments': typeof AuthenticatedSettingsDepartmentsIndexRoute
  '/settings/rooms': typeof AuthenticatedSettingsRoomsIndexRoute
  '/settings/staff': typeof AuthenticatedSettingsStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/ui-test': typeof UiTestRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/platform/clinics/new': typeof AuthenticatedPlatformClinicsNewRoute
  '/_authenticated/settings/departments/$departmentId': typeof AuthenticatedSettingsDepartmentsDepartmentIdRoute
  '/_authenticated/settings/departments/new': typeof AuthenticatedSettingsDepartmentsNewRoute
  '/_authenticated/settings/rooms/$roomId': typeof AuthenticatedSettingsRoomsRoomIdRoute
  '/_authenticated/settings/rooms/new': typeof AuthenticatedSettingsRoomsNewRoute
  '/_authenticated/settings/staff/$staffId': typeof AuthenticatedSettingsStaffStaffIdRoute
  '/_authenticated/settings/staff/invite': typeof AuthenticatedSettingsStaffInviteRoute
  '/_authenticated/platform/clinics/': typeof AuthenticatedPlatformClinicsIndexRoute
  '/_authenticated/settings/departments/': typeof AuthenticatedSettingsDepartmentsIndexRoute
  '/_authenticated/settings/rooms/': typeof AuthenticatedSettingsRoomsIndexRoute
  '/_authenticated/settings/staff/': typeof AuthenticatedSettingsStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/ui-test'
    | '/dashboard'
    | '/platform/clinics/new'
    | '/settings/departments/$departmentId'
    | '/settings/departments/new'
    | '/settings/rooms/$roomId'
    | '/settings/rooms/new'
    | '/settings/staff/$staffId'
    | '/settings/staff/invite'
    | '/platform/clinics/'
    | '/settings/departments/'
    | '/settings/rooms/'
    | '/settings/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/ui-test'
    | '/dashboard'
    | '/platform/clinics/new'
    | '/settings/departments/$departmentId'
    | '/settings/departments/new'
    | '/settings/rooms/$roomId'
    | '/settings/rooms/new'
    | '/settings/staff/$staffId'
    | '/settings/staff/invite'
    | '/platform/clinics'
    | '/settings/departments'
    | '/settings/rooms'
    | '/settings/staff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/login'
    | '/ui-test'
    | '/_authenticated/dashboard'
    | '/_authenticated/platform/clinics/new'
    | '/_authenticated/settings/departments/$departmentId'
    | '/_authenticated/settings/departments/new'
    | '/_authenticated/settings/rooms/$roomId'
    | '/_authenticated/settings/rooms/new'
    | '/_authenticated/settings/staff/$staffId'
    | '/_authenticated/settings/staff/invite'
    | '/_authenticated/platform/clinics/'
    | '/_authenticated/settings/departments/'
    | '/_authenticated/settings/rooms/'
    | '/_authenticated/settings/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  UiTestRoute: typeof UiTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-test': {
      id: '/ui-test'
      path: '/ui-test'
      fullPath: '/ui-test'
      preLoaderRoute: typeof UiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/staff/': {
      id: '/_authenticated/settings/staff/'
      path: '/settings/staff'
      fullPath: '/settings/staff/'
      preLoaderRoute: typeof AuthenticatedSettingsStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/rooms/': {
      id: '/_authenticated/settings/rooms/'
      path: '/settings/rooms'
      fullPath: '/settings/rooms/'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/departments/': {
      id: '/_authenticated/settings/departments/'
      path: '/settings/departments'
      fullPath: '/settings/departments/'
      preLoaderRoute: typeof AuthenticatedSettingsDepartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/clinics/': {
      id: '/_authenticated/platform/clinics/'
      path: '/platform/clinics'
      fullPath: '/platform/clinics/'
      preLoaderRoute: typeof AuthenticatedPlatformClinicsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/staff/invite': {
      id: '/_authenticated/settings/staff/invite'
      path: '/settings/staff/invite'
      fullPath: '/settings/staff/invite'
      preLoaderRoute: typeof AuthenticatedSettingsStaffInviteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/staff/$staffId': {
      id: '/_authenticated/settings/staff/$staffId'
      path: '/settings/staff/$staffId'
      fullPath: '/settings/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedSettingsStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/rooms/new': {
      id: '/_authenticated/settings/rooms/new'
      path: '/settings/rooms/new'
      fullPath: '/settings/rooms/new'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/rooms/$roomId': {
      id: '/_authenticated/settings/rooms/$roomId'
      path: '/settings/rooms/$roomId'
      fullPath: '/settings/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRoomIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/departments/new': {
      id: '/_authenticated/settings/departments/new'
      path: '/settings/departments/new'
      fullPath: '/settings/departments/new'
      preLoaderRoute: typeof AuthenticatedSettingsDepartmentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/departments/$departmentId': {
      id: '/_authenticated/settings/departments/$departmentId'
      path: '/settings/departments/$departmentId'
      fullPath: '/settings/departments/$departmentId'
      preLoaderRoute: typeof AuthenticatedSettingsDepartmentsDepartmentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/clinics/new': {
      id: '/_authenticated/platform/clinics/new'
      path: '/platform/clinics/new'
      fullPath: '/platform/clinics/new'
      preLoaderRoute: typeof AuthenticatedPlatformClinicsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlatformClinicsNewRoute: typeof AuthenticatedPlatformClinicsNewRoute
  AuthenticatedSettingsDepartmentsDepartmentIdRoute: typeof AuthenticatedSettingsDepartmentsDepartmentIdRoute
  AuthenticatedSettingsDepartmentsNewRoute: typeof AuthenticatedSettingsDepartmentsNewRoute
  AuthenticatedSettingsRoomsRoomIdRoute: typeof AuthenticatedSettingsRoomsRoomIdRoute
  AuthenticatedSettingsRoomsNewRoute: typeof AuthenticatedSettingsRoomsNewRoute
  AuthenticatedSettingsStaffStaffIdRoute: typeof AuthenticatedSettingsStaffStaffIdRoute
  AuthenticatedSettingsStaffInviteRoute: typeof AuthenticatedSettingsStaffInviteRoute
  AuthenticatedPlatformClinicsIndexRoute: typeof AuthenticatedPlatformClinicsIndexRoute
  AuthenticatedSettingsDepartmentsIndexRoute: typeof AuthenticatedSettingsDepartmentsIndexRoute
  AuthenticatedSettingsRoomsIndexRoute: typeof AuthenticatedSettingsRoomsIndexRoute
  AuthenticatedSettingsStaffIndexRoute: typeof AuthenticatedSettingsStaffIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlatformClinicsNewRoute: AuthenticatedPlatformClinicsNewRoute,
  AuthenticatedSettingsDepartmentsDepartmentIdRoute:
    AuthenticatedSettingsDepartmentsDepartmentIdRoute,
  AuthenticatedSettingsDepartmentsNewRoute:
    AuthenticatedSettingsDepartmentsNewRoute,
  AuthenticatedSettingsRoomsRoomIdRoute: AuthenticatedSettingsRoomsRoomIdRoute,
  AuthenticatedSettingsRoomsNewRoute: AuthenticatedSettingsRoomsNewRoute,
  AuthenticatedSettingsStaffStaffIdRoute:
    AuthenticatedSettingsStaffStaffIdRoute,
  AuthenticatedSettingsStaffInviteRoute: AuthenticatedSettingsStaffInviteRoute,
  AuthenticatedPlatformClinicsIndexRoute:
    AuthenticatedPlatformClinicsIndexRoute,
  AuthenticatedSettingsDepartmentsIndexRoute:
    AuthenticatedSettingsDepartmentsIndexRoute,
  AuthenticatedSettingsRoomsIndexRoute: AuthenticatedSettingsRoomsIndexRoute,
  AuthenticatedSettingsStaffIndexRoute: AuthenticatedSettingsStaffIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  UiTestRoute: UiTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
