/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiTestRouteImport } from './routes/ui-test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRoomsRouteImport } from './routes/_authenticated/settings/rooms'
import { Route as AuthenticatedSettingsDepartmentsRouteImport } from './routes/_authenticated/settings/departments'
import { Route as AuthenticatedSettingsStaffIndexRouteImport } from './routes/_authenticated/settings/staff/index'
import { Route as AuthenticatedPlatformClinicsIndexRouteImport } from './routes/_authenticated/platform/clinics/index'
import { Route as AuthenticatedSettingsStaffInviteRouteImport } from './routes/_authenticated/settings/staff/invite'
import { Route as AuthenticatedSettingsStaffStaffIdRouteImport } from './routes/_authenticated/settings/staff/$staffId'
import { Route as AuthenticatedPlatformClinicsNewRouteImport } from './routes/_authenticated/platform/clinics/new'

const UiTestRoute = UiTestRouteImport.update({
  id: '/ui-test',
  path: '/ui-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoomsRoute =
  AuthenticatedSettingsRoomsRouteImport.update({
    id: '/settings/rooms',
    path: '/settings/rooms',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsDepartmentsRoute =
  AuthenticatedSettingsDepartmentsRouteImport.update({
    id: '/settings/departments',
    path: '/settings/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsStaffIndexRoute =
  AuthenticatedSettingsStaffIndexRouteImport.update({
    id: '/settings/staff/',
    path: '/settings/staff/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformClinicsIndexRoute =
  AuthenticatedPlatformClinicsIndexRouteImport.update({
    id: '/platform/clinics/',
    path: '/platform/clinics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsStaffInviteRoute =
  AuthenticatedSettingsStaffInviteRouteImport.update({
    id: '/settings/staff/invite',
    path: '/settings/staff/invite',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsStaffStaffIdRoute =
  AuthenticatedSettingsStaffStaffIdRouteImport.update({
    id: '/settings/staff/$staffId',
    path: '/settings/staff/$staffId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformClinicsNewRoute =
  AuthenticatedPlatformClinicsNewRouteImport.update({
    id: '/platform/clinics/new',
    path: '/platform/clinics/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ui-test': typeof UiTestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/settings/rooms': typeof AuthenticatedSettingsRoomsRoute
  '/platform/clinics/new': typeof AuthenticatedPlatformClinicsNewRoute
  '/settings/staff/$staffId': typeof AuthenticatedSettingsStaffStaffIdRoute
  '/settings/staff/invite': typeof AuthenticatedSettingsStaffInviteRoute
  '/platform/clinics/': typeof AuthenticatedPlatformClinicsIndexRoute
  '/settings/staff/': typeof AuthenticatedSettingsStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ui-test': typeof UiTestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/settings/rooms': typeof AuthenticatedSettingsRoomsRoute
  '/platform/clinics/new': typeof AuthenticatedPlatformClinicsNewRoute
  '/settings/staff/$staffId': typeof AuthenticatedSettingsStaffStaffIdRoute
  '/settings/staff/invite': typeof AuthenticatedSettingsStaffInviteRoute
  '/platform/clinics': typeof AuthenticatedPlatformClinicsIndexRoute
  '/settings/staff': typeof AuthenticatedSettingsStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/ui-test': typeof UiTestRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/_authenticated/settings/rooms': typeof AuthenticatedSettingsRoomsRoute
  '/_authenticated/platform/clinics/new': typeof AuthenticatedPlatformClinicsNewRoute
  '/_authenticated/settings/staff/$staffId': typeof AuthenticatedSettingsStaffStaffIdRoute
  '/_authenticated/settings/staff/invite': typeof AuthenticatedSettingsStaffInviteRoute
  '/_authenticated/platform/clinics/': typeof AuthenticatedPlatformClinicsIndexRoute
  '/_authenticated/settings/staff/': typeof AuthenticatedSettingsStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ui-test'
    | '/dashboard'
    | '/settings/departments'
    | '/settings/rooms'
    | '/platform/clinics/new'
    | '/settings/staff/$staffId'
    | '/settings/staff/invite'
    | '/platform/clinics/'
    | '/settings/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ui-test'
    | '/dashboard'
    | '/settings/departments'
    | '/settings/rooms'
    | '/platform/clinics/new'
    | '/settings/staff/$staffId'
    | '/settings/staff/invite'
    | '/platform/clinics'
    | '/settings/staff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/ui-test'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings/departments'
    | '/_authenticated/settings/rooms'
    | '/_authenticated/platform/clinics/new'
    | '/_authenticated/settings/staff/$staffId'
    | '/_authenticated/settings/staff/invite'
    | '/_authenticated/platform/clinics/'
    | '/_authenticated/settings/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UiTestRoute: typeof UiTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-test': {
      id: '/ui-test'
      path: '/ui-test'
      fullPath: '/ui-test'
      preLoaderRoute: typeof UiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/rooms': {
      id: '/_authenticated/settings/rooms'
      path: '/settings/rooms'
      fullPath: '/settings/rooms'
      preLoaderRoute: typeof AuthenticatedSettingsRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/departments': {
      id: '/_authenticated/settings/departments'
      path: '/settings/departments'
      fullPath: '/settings/departments'
      preLoaderRoute: typeof AuthenticatedSettingsDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/staff/': {
      id: '/_authenticated/settings/staff/'
      path: '/settings/staff'
      fullPath: '/settings/staff/'
      preLoaderRoute: typeof AuthenticatedSettingsStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/clinics/': {
      id: '/_authenticated/platform/clinics/'
      path: '/platform/clinics'
      fullPath: '/platform/clinics/'
      preLoaderRoute: typeof AuthenticatedPlatformClinicsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/staff/invite': {
      id: '/_authenticated/settings/staff/invite'
      path: '/settings/staff/invite'
      fullPath: '/settings/staff/invite'
      preLoaderRoute: typeof AuthenticatedSettingsStaffInviteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/staff/$staffId': {
      id: '/_authenticated/settings/staff/$staffId'
      path: '/settings/staff/$staffId'
      fullPath: '/settings/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedSettingsStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/clinics/new': {
      id: '/_authenticated/platform/clinics/new'
      path: '/platform/clinics/new'
      fullPath: '/platform/clinics/new'
      preLoaderRoute: typeof AuthenticatedPlatformClinicsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsDepartmentsRoute: typeof AuthenticatedSettingsDepartmentsRoute
  AuthenticatedSettingsRoomsRoute: typeof AuthenticatedSettingsRoomsRoute
  AuthenticatedPlatformClinicsNewRoute: typeof AuthenticatedPlatformClinicsNewRoute
  AuthenticatedSettingsStaffStaffIdRoute: typeof AuthenticatedSettingsStaffStaffIdRoute
  AuthenticatedSettingsStaffInviteRoute: typeof AuthenticatedSettingsStaffInviteRoute
  AuthenticatedPlatformClinicsIndexRoute: typeof AuthenticatedPlatformClinicsIndexRoute
  AuthenticatedSettingsStaffIndexRoute: typeof AuthenticatedSettingsStaffIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsDepartmentsRoute: AuthenticatedSettingsDepartmentsRoute,
  AuthenticatedSettingsRoomsRoute: AuthenticatedSettingsRoomsRoute,
  AuthenticatedPlatformClinicsNewRoute: AuthenticatedPlatformClinicsNewRoute,
  AuthenticatedSettingsStaffStaffIdRoute:
    AuthenticatedSettingsStaffStaffIdRoute,
  AuthenticatedSettingsStaffInviteRoute: AuthenticatedSettingsStaffInviteRoute,
  AuthenticatedPlatformClinicsIndexRoute:
    AuthenticatedPlatformClinicsIndexRoute,
  AuthenticatedSettingsStaffIndexRoute: AuthenticatedSettingsStaffIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UiTestRoute: UiTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
