import {
  Activity,
  AlertTriangle,
  AlignCenter,
  ArrowRight,
  ArrowUpRight,
  Award,
  BarChart3,
  Bell,
  Calendar,
  ChevronDown,
  ChevronRight,
  Code,
  Command,
  CreditCard,
  FileInput,
  FileText,
  FileX,
  Folder,
  Gauge,
  GaugeCircle,
  Layers,
  Layout,
  List,
  Loader2,
  MessageSquare,
  Minus,
  MoreHorizontal,
  MousePointer,
  Navigation,
  Package,
  Paintbrush,
  Palette,
  PanelLeft,
  RotateCcw,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Square,
  Star,
  Table,
  Target,
  TrendingUp,
  Type,
  Upload,
  User,
  Zap,
} from 'lucide-react';
import type { ElementType } from 'react';

// Category icons mapping
export const categoryIcons: Record<string, ElementType> = {
  'Base components': Layers,
  'Application UI': Zap,
  Marketing: Star,
  Documentation: FileText,
};

// Component icons mapping
export const componentIcons: Record<string, ElementType> = {
  // Documentation
  'Read Me': FileText,
  Typography: Type,
  'System Colors': Palette,
  Icons: Star,

  // Base components
  Buttons: MousePointer,
  Forms: FileInput,
  Input: Type,
  Layout: Layout,
  'HR Cards': CreditCard,
  Accordion: ChevronDown,
  Navigation: Navigation,
  Breadcrumbs: ChevronRight,
  Pagination: MoreHorizontal,
  Interaction: MousePointer,
  Badges: Award,
  Alerts: AlertTriangle,
  'Data Display': BarChart3,
  Charts: BarChart3,
  Lists: List,
  Skeletons: User,
  Modals: Square,
  Drawer: PanelLeft,
  Avatars: User,
  'File Upload': Upload,
  Miscellaneous: Settings,

  // Application UI - Specific components from reference image
  'Section footers': AlignCenter,
  'Header navigations': ArrowRight,
  'Activity gauges': GaugeCircle,
  'Slideout menus': SlidersHorizontal,
  'Inline CTAs': Target,
  Carousels: RotateCcw,
  'Progress steps': ArrowUpRight,
  'Activity feeds': Activity,
  Messaging: MessageSquare,
  Tabs: Folder,
  Tables: Table,
  Notifications: Bell,
  Calendars: Calendar,
  'Content dividers': Minus,
  'Loading indicators': Loader2,
  'Empty states': FileX,
  'Code snippets': Code,
  'Auth Card': ShieldCheck,

  // Existing Application UI
  Dashboard: Gauge,
  'Simple Insight': TrendingUp,
  'Color Picker': Paintbrush,
  'Command Menu': Command,
  'Text Editor': Type,
  Status: Activity,
  'Page Headers': Layout,
  'Card Headers': CreditCard,

  // Default fallback
  Default: Package,
};
