name: habe-final

services:
  postgres:
    image: postgres
    container_name: habe-final-postgres
    environment:
      POSTGRES_DB: habe-final
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - habe-final_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  habe-final_postgres_data:
